"""migrate_to_supabase

Revision ID: 5f4a82c6144a
Revises: a4d6136abcf7
Create Date: 2025-06-02 21:20:18.281412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4a82c6144a'
down_revision: Union[str, None] = 'a4d6136abcf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'analysis_response')
    op.drop_column('messages', 'has_analysis')
    op.add_column('users', sa.Column('supabase_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    op.drop_column('users', 'auth0_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    op.drop_column('users', 'email')
    op.drop_column('users', 'supabase_id')
    op.add_column('messages', sa.Column('has_analysis', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('analysis_response', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
